# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

        # Install Python Dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

        # Build App and Run Application Test
      - name: Build Application and Run unit Test
        run: python run.py & pytest
  deploy:

    runs-on: self-hosted
    steps:
      - name: clear previous run
        run: sudo kill -9 $(sudo lsof -t -i:8081)
      - name: init deploy
        run: sudo rm -rf github_action_demo/
      - name: pulling repo
        run: git clone https://github.com/khongtrunght/github_action_demo.git
      - name: checkout repo
        run: cd github_action_demo/
      - name: Install Python 3.6
        run: sudo apt-get update & sudo apt-get install python3.6 & python3 --version
      - name: Install dependencies
        run: sudo apt install python3-pip -y & sudo pip3 install -r requirements.txt
      - name: Deploy App
        run: sudo python3 main.py
